spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/transacoes
    password: root
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/auth/realms/Transacoes
          jwk-set-uri: http://localhost:18080/auth/realms/Transacoes/protocol/openid-connect/certs
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: transacoes-consumer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    topic: transacoes
    bootstrap-servers: ${KAFKA_HOST:localhost:9092}